#ifndef GUARD_FRONTIER_INTRO_TUTORIAL_H
#define GUARD_FRONTIER_INTRO_TUTORIAL_H

enum FrontierIntroTutorialCheckpoint
{
    FRONTIER_INTRO_CHECKPOINT_NONE,
    FRONTIER_INTRO_CHECKPOINT_POKENAV_MAIN,
    FRONTIER_INTRO_CHECKPOINT_POKENAV_CONDITION,
    FRONTIER_INTRO_CHECKPOINT_TEAM_LAB_PARTY,
    FRONTIER_INTRO_CHECKPOINT_TEAM_LAB_EDITOR,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_LIST,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_SEARCH_TOP,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_SEARCH_MENU,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_SEARCH_PARAMETER,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_SEARCH_COMPLETE,
    FRONTIER_INTRO_CHECKPOINT_POKEDEX_RESULTS,
    FRONTIER_INTRO_CHECKPOINT_TEAM_LAB_ITEM,
    FRONTIER_INTRO_CHECKPOINT_NAMING_SCREEN,
};

void StartFrontierIntroTutorial(void);
void FrontierIntroTutorial_ApplyInput(void);
void FrontierIntroTutorial_NotifyReady(u8 checkpoint);
bool8 FrontierIntroTutorial_IsSkipping(void);
void FrontierIntroTutorial_CompleteSkip(void);

#endif // GUARD_FRONTIER_INTRO_TUTORIAL_H
